### ISSUE TITLE
Search with `{` seems to return 0 results

### ISSUE THREAD

**Issue by beinginorbit** [thieman/better-search#13]
Searching for something like `<Div css={` returns no results when it should otherwise. This is on OSX.

**Comment by thieman** [comment]
Confirming a similar issue on Linux, it's not having the ~angle brackets~ braces. Gonna try to get a fix out now.

**Comment by thieman** [comment]
Fixed in https://github.com/thieman/better-search/commit/41a186b3955b61450174905e0ea5b30bc547faa7

Turns out we were defaulting to treating the query as a regex, which is why braces made it sad. We now default to treating the query as a literal, and added the regex support as an option in full search.
