### ISSUE TITLE
doesnt seem to do anything

### ISSUE THREAD

**Issue by petervijeh** [thieman/better-search#19]
this plugin does not seem to work :/

**Comment by thieman** [comment]
Thanks for the report, could you please share info about your OS and version of VS Code, along with any error messages being reported in the console?

**Comment by mlunoe** [comment]
I hit this issue as well. Apparently, Better Search does not do anything when no files are open.

I created a small video here illustrating the bug:
![](https://cl.ly/abacfa4d8b05/Screen%20Recording%202019-10-08%20at%2001.54%20PM.gif)

First part of the video:
1. The extension panel open (only), then try to do a "Better Search: Quick Find"
2. Nothing happens. Expected: search results to be displayed in a new tab

Second part:
1. I open any file from the file list in the side bar
2. Then I run "Better Search: Quick Find"
3. Search results are displayed in a new file. This is expected behaviour

**Comment by mlunoe** [comment]
Also, the instructions could be a bit more explanatory here: https://marketplace.visualstudio.com/items?itemName=travisthieman.better-search

E.g. step 1 could read:
> Hit Cmd + P and type to find "Better Seach: Quick Find" and hit enter to run the command

As it is right now, when nothing happens, it is not clear whether I am running it in the right place, so this sentence is not very helpful as it specifies the internal name of the command and does not specify where to run it:
> Run betterSearch.search to start a search with default options

**Comment by thieman** [comment]
@mlunoe Thanks for the additional info, this sounds like it's hopefully a pretty simple context-descriptor bug. I'll try to fix it up this weekend.

**Comment by thieman** [comment]
Fixed by https://github.com/thieman/better-search/commit/2696f0cf364e79f18e0638df9cf179ab1d189851, will have this in a release by end of weekend
